
export const tools = [
    {
        id: 1,
        title: 'Codemint ChatBot 🎉',
        link: '/tools/chatGPT',
        semicontent:'Introducing Codemint ChatBot🎉: We are excited to introduce Codemint ChatBot',
        content: `Introducing Codemint ChatBot🎉: We are excited to introduce Codemint ChatBot, powered by ChatGPT. This chatbot is designed to provide you with valuable information and assistance. Whether you have questions about coding, artificial intelligence, or anything else, Codemint ChatBot is here to help. Our team has worked hard to make this chatbot a valuable resource for you, and we can't wait for you to try it out.`,
        author: 'ADil Sarfraz',
        date: '2023-09-05',
        video: 'https://img.playbook.com/6oXJCbkRo2ClNKip-lu5mb_xvkzgicVXx_L_mqoGjlw/Z3M6Ly9wbGF5Ym9v/ay1hc3NldHMtcHVi/bGljLzA5MDliNWJm/LTc0YzItNDhjNC04/ZTBkLWM2OGMwOTM3/YTg3Yg',
        img:'https://images.pexels.com/photos/8728380/pexels-photo-8728380.jpeg?auto=compress&cs=tinysrgb&w=760&h=750&dpr=1',
    },
    {
        id: 2,
        title: 'Image Generator 😍',
        link: '/tools/textToImage',
        semicontent:`Image Generator: In this blog post, we'll take you on a journey through our innovative Image Generator tool`,
        content: `Image Generator: In this blog post, we'll take you on a journey through our innovative Image Generator tool. With Codemint ChatGPT, you can easily create stunning images with just a few clicks. Whether you're a designer, a developer, or anyone interested in image generation, this tool is a must-try. We'll explore its features and show you how to get started.`,
        author: 'ADil Sarfraz',
        date: '2023-07-17',
        video: 'https://img.playbook.com/gV8ZajyGXIFMSvIT5uJo2LOXl7NbmNgeFUO-dJsVgAo/Z3M6Ly9wbGF5Ym9v/ay1hc3NldHMtcHVi/bGljLzQyZDY4MjIx/LTA4MGYtNGEwYy1h/M2MxLWI1NmQ4Y2Nl/MWFlYw',
        img: 'https://nextui.org/blog/v2.1.0.jpg?auto=compress&cs=tinysrgb&w=760&dpr=1',
    },
    {
        id: 3,
        title: 'Text To Speech ✨',
        link: '/tools/textToSpeech',
        semicontent:'Background Remover: Have you ever wanted to remove the background from an image effortlessly?',
        content: `Background Remover: Have you ever wanted to remove the background from an image effortlessly? With Codemint ChatGPT's Background Remover tool, it's easier than ever. In this blog post, we'll show you how to use this powerful tool to create stunning images with transparent backgrounds. Whether you're a photographer, a graphic designer, or just someone who loves editing photos, this tool is a game-changer.`,
        author: 'ADil Sarfraz',
        date: '2020-02-04',
        video:'https://img.playbook.com/5AvpCDwBmONNkDyxaCU91sVVcbQ0HtceoAELkcMtB6s/Z3M6Ly9wbGF5Ym9v/ay1hc3NldHMtcHVi/bGljLzQ3ZTFkNTBl/LTMwOTQtNDQ5NS1h/NTgxLWY0MDQzNWEy/YjEzOQ',
        img: 'https://images.pexels.com/photos/8721318/pexels-photo-8721318.jpeg?auto=compress&cs=tinysrgb&w=760&h=750&dpr=1',
    },
    // {
    //     id: 3,
    //     title: 'Background Remover',
    //     link: '/tools',
    //     semicontent:'Background Remover: Have you ever wanted to remove the background from an image effortlessly?',
    //     content: `Background Remover: Have you ever wanted to remove the background from an image effortlessly? With Codemint ChatGPT's Background Remover tool, it's easier than ever. In this blog post, we'll show you how to use this powerful tool to create stunning images with transparent backgrounds. Whether you're a photographer, a graphic designer, or just someone who loves editing photos, this tool is a game-changer.`,
    //     author: 'ADil Sarfraz',
    //     date: '2020-02-04',
    //     video:'https://img.playbook.com/z_sx55qJzfadcNdZxoWE6kC6aHznk5cbQZ0KduiuJis/Z3M6Ly9wbGF5Ym9v/ay1hc3NldHMtcHVi/bGljL2JkZmIxMTRh/LTQ2NWQtNDJhYS05/ZGQwLTkzNDdiYjM5/ODlkYw',
    //     img: 'https://images.pexels.com/photos/8721318/pexels-photo-8721318.jpeg?auto=compress&cs=tinysrgb&w=760&h=750&dpr=1',
    // },
  ];
  